# This is a basic workflow to help you get started with Actions

name: Chrome headless
on: 
  push:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
