# This is a basic workflow to help you get started with Actions

name: Chrome headless
on: 
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          
      - name: Generate Allure report
        if: always()
        uses: QuintilianoNery/action-allure-report-V2@0.2.0
            
      - name: Commit report results
        if: always()
        run: |
            git config --local user.email "xuanbach174@gmail.com"
            git config --local user.name "xuanbach174"
            git add allure-report -f
            git add allure-results -f
            git commit -m "[chore] autogenerate Allure report" -a

      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
            github_token: '${{ secrets.GITHUB_TOKEN }}'
            force: true